apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment 
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - image: murali25420/nginx-test:latest
        name: nginx-test
        ports:
        - containerPort: 80
